### ISSUE TITLE
Plugin isn't working..?

### ISSUE THREAD

**Issue by raffel080108** [LOOHP/HoloMobHealth#11]
**Latest Version 2.2.4.11**
Getting this error on console:
```
23.02 21:06:21 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:908) ~[purpur-1.18.1.jar:git-Purpur-"4afe68b"]
23.02 21:06:21 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2372) ~[?:?]
23.02 21:06:21 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2183) ~[?:?]
23.02 21:06:21 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2164) ~[?:?]
23.02 21:06:21 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
23.02 21:06:21 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
23.02 21:06:21 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
23.02 21:06:21 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-"4afe68b"]
23.02 21:06:21 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
23.02 21:06:21 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
23.02 21:06:21 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[purpur-1.18.1.jar:git-Purpur-"4afe68b"]
23.02 21:06:21 [Server] INFO at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-"4afe68b"]
23.02 21:06:21 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
23.02 21:06:21 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1427) ~[purpur-1.18.1.jar:git-Purpur-"4afe68b"]
23.02 21:06:21 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1420) ~[purpur-1.18.1.jar:git-Purpur-"4afe68b"]
23.02 21:06:25 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
23.02 21:06:25 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1555) ~[purpur-1.18.1.jar:git-Purpur-"4afe68b"]
23.02 21:06:25 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1294) ~[purpur-1.18.1.jar:git-Purpur-"4afe68b"]
23.02 21:06:25 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-"4afe68b"]
23.02 21:06:25 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
23.02 21:06:25 [Server] INFO Caused by: org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ProtocolLib]. Please download and install these plugins to run 'HoloMobHealth v2.2.4.11'.
23.02 21:06:25 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
23.02 21:06:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
23.02 21:06:25 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:294) ~[PlugManX.jar:?]
23.02 21:06:25 [Server] INFO at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[PlugManX.jar:?]
23.02 21:06:25 [Server] INFO at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugManX.jar:?]
23.02 21:06:25 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
23.02 21:06:25 [Server] INFO ... 21 more
```

**Comment by LOOHP** [comment]
```
23.02 21:06:25 [Server] INFO Caused by: org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ProtocolLib]. Please download and install these plugins to run 'HoloMobHealth v2.2.4.11'.
```

**Comment by raffel080108** [comment]
Yea, I'm blind - Sorry lol
Having a bad day or something I'm missing the most obvious things right now lol xD
