### ISSUE TITLE
Got lots of errors

### ISSUE THREAD

**Issue by PeterMa9621** [LOOHP/HoloMobHealth#13]
I am keeping getting this error. It works correctly before, but when I change `AlwaysShow: true` to `AlwaysShow: false`, it's not working. I am using multi-line.
```
[HoloMobHealth] Task #9922 for HoloMobHealth v2.2.5.10 generated an exception
java.lang.NoClassDefFoundError: com/loohp/holomobhealth/libs/org/apache/commons/lang/Validate
        at com.loohp.holomobhealth.utils.BoundingBox.of(BoundingBox.java:66) ~[HoloMobHealth-2.2.5.10.jar:?]
        at com.loohp.holomobhealth.utils.BoundingBoxUtils.getBoundingBox(BoundingBoxUtils.java:62) ~[HoloMobHealth-2.2.5.10.jar:?]
        at com.loohp.holomobhealth.utils.RayTrace.getLookingEntity(RayTrace.java:47) ~[HoloMobHealth-2.2.5.10.jar:?]
        at com.loohp.holomobhealth.modules.ArmorstandDisplay.lambda$run$0(ArmorstandDisplay.java:107) ~[HoloMobHealth-2.2.5.10.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-247]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-247]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-247]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.loohp.holomobhealth.libs.org.apache.commons.lang.Validate
        ... 12 more

**Comment by LOOHP** [comment]
Should be fixed in 2.2.5.11
