### ISSUE TITLE
warn spam if i add this plugin

### ISSUE THREAD

**Issue by SladeGit** [LOOHP/HoloMobHealth#19]
[21:35:09] [Server thread/WARN]: java.lang.NoSuchFieldException: P
[21:35:09] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2642)
[21:35:09] [Server thread/WARN]: 	at HoloMobHealth-2.3.1.0.jar//com.loohp.holomobhealth.utils.NMSUtils.<clinit>(NMSUtils.java:136)
[21:35:09] [Server thread/WARN]: 	at HoloMobHealth-2.3.1.0.jar//com.loohp.holomobhealth.modules.NameTagDisplay$3.onPacketSending(NameTagDisplay.java:147)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:570)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:473)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:432)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:379)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2164)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2150)
[21:35:09] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[21:35:09] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.utils.reflect.ReflectMethod.invoke(ReflectMethod.java:35)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.nms.NMS.sendPacket(NMS.java:232)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntity(NMS_1_17.java:220)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntityLiving(NMS_1_17.java:259)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntityArmorStand(NMS_1_17.java:296)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.show(HologramLine.java:394)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$showPageTo$4(Hologram.java:395)
[21:35:09] [Server thread/WARN]: 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.holograms.Hologram.showPageTo(Hologram.java:395)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.holograms.Hologram.show(Hologram.java:383)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.holograms.HologramManager.updateVisibility(HologramManager.java:78)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.holograms.HologramManager.updateVisibility(HologramManager.java:72)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.player.PlayerListener.onJoin(PlayerListener.java:23)
[21:35:09] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor217.execute(Unknown Source)
[21:35:09] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[21:35:09] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:35:09] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:35:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:372)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$0(PlayerList.java:309)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1389)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[21:35:09] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[21:35:09] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.setAccessible(boolean)" because "com.loohp.holomobhealth.utils.NMSUtils.nmsWorldEntityManagerField" is null
[21:35:09] [Server thread/WARN]: 	at HoloMobHealth-2.3.1.0.jar//com.loohp.holomobhealth.utils.NMSUtils.getEntityUUIDFromID(NMSUtils.java:153)
[21:35:09] [Server thread/WARN]: 	at HoloMobHealth-2.3.1.0.jar//com.loohp.holomobhealth.modules.NameTagDisplay$3.onPacketSending(NameTagDisplay.java:147)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:570)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:473)
[21:35:09] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:432)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:379)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2164)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2150)
[21:35:09] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[21:35:09] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.utils.reflect.ReflectMethod.invoke(ReflectMethod.java:35)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.nms.NMS.sendPacket(NMS.java:232)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntity(NMS_1_17.java:220)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntityLiving(NMS_1_17.java:259)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntityArmorStand(NMS_1_17.java:296)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.show(HologramLine.java:394)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$showPageTo$4(Hologram.java:395)
[21:35:09] [Server thread/WARN]: 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.holograms.Hologram.showPageTo(Hologram.java:395)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.holograms.Hologram.show(Hologram.java:383)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.holograms.HologramManager.updateVisibility(HologramManager.java:78)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.holograms.HologramManager.updateVisibility(HologramManager.java:72)
[21:35:09] [Server thread/WARN]: 	at DecentHolograms.jar//eu.decentsoftware.holograms.api.player.PlayerListener.onJoin(PlayerListener.java:23)
[21:35:09] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor217.execute(Unknown Source)
[21:35:09] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[21:35:09] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:35:09] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:35:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:372)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$0(PlayerList.java:309)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1389)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[21:35:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[21:35:09] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[21:35:09] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.setAccessible(boolean)" because "com.loohp.holomobhealth.utils.NMSUtils.nmsWorldEntityManagerField" is null
[21:35:09] [Server thread/WARN]: 	at HoloMobHealth-2.3.1.0.jar//com.loohp.holomobhealth.utils.NMSUtils.getEntityUUIDFromID(NMSUtils.java:153)
[21:35:09] [Server thread/WARN]: 	at HoloMobHealth-2.3.1.0.jar//com.loohp.holomobhealth.modules.NameTagDisplay$3.onPacketSending(NameTagDisplay.java:147)

MC 1.19.2
plugin latest
papermc latest

**Comment by LOOHP** [comment]
Update to the latest dev build

**Comment by SladeGit** [comment]
how can i find the lastest dev build?

**Comment by SladeGit** [comment]
it is HoloMobHealth-2.3.1.0.jar

**Comment by SladeGit** [comment]
ProtocolLib-5.0.0-SNAPSHOT was i too testing, same warning

**Comment by LOOHP** [comment]
https://ci.loohpjames.com
