### ISSUE TITLE
Warning in Console and Error

### ISSUE THREAD

**Issue by JiangQiYan713** [LOOHP/HoloMobHealth#21]
The console continuously outputs warnings, and the display function cannot be executed
It may be caused by PaperMC update
![image](https://user-images.githubusercontent.com/91627081/195918114-51ecae03-00c3-47a5-994f-64f449ea6090.png)

Version:
Paper MC git-Paper-211 (MC: 1.19.2)
ProtocolLib #600
HoloMobHealth 2.3.1.0

Console Log:
```
[02:26:10] [Server thread/WARN]: java.lang.NoSuchFieldException: P
[02:26:10] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[02:26:10] [Server thread/WARN]: 	at HoloMobHealth-2.3.1.0.jar//com.loohp.holomobhealth.utils.NMSUtils.<clinit>(NMSUtils.java:136)
[02:26:10] [Server thread/WARN]: 	at HoloMobHealth-2.3.1.0.jar//com.loohp.holomobhealth.modules.DamageIndicator.regen(DamageIndicator.java:375)
[02:26:10] [Server thread/WARN]: 	at HoloMobHealth-2.3.1.0.jar//com.loohp.holomobhealth.modules.DamageIndicator.onRegen(DamageIndicator.java:327)
[02:26:10] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor230.execute(Unknown Source)
[02:26:10] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[02:26:10] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[02:26:10] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:26:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.heal(EntityLiving.java:1268)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.heal(EntityLiving.java:1257)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.world.entity.animal.horse.EntityHorseAbstract.w_(EntityHorseAbstract.java:565)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.k(EntityLiving.java:2975)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityInsentient.k(EntityInsentient.java:402)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.world.entity.animal.horse.EntityHorseAbstract.k(EntityHorseAbstract.java:600)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.server.level.WorldServer.a(WorldServer.java:1190)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.world.level.World.a(World.java:897)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.server.level.WorldServer.lambda$tick$6(WorldServer.java:728)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:42)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.server.level.WorldServer.a(WorldServer.java:708)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1535)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[02:26:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[02:26:10] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

```
[02:26:54] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.setAccessible(boolean)" because "com.loohp.holomobhealth.utils.NMSUtils.nmsWorldEntityManagerField" is null
[02:26:54] [Server thread/WARN]: 	at HoloMobHealth-2.3.1.0.jar//com.loohp.holomobhealth.utils.NMSUtils.getEntityUUIDFromID(NMSUtils.java:153)
[02:26:54] [Server thread/WARN]: 	at HoloMobHealth-2.3.1.0.jar//com.loohp.holomobhealth.modules.NameTagDisplay$3.onPacketSending(NameTagDisplay.java:147)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:570)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:473)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:432)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:379)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2165)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2151)
[02:26:54] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
[02:26:54] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:26:54] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.utils.reflect.ReflectMethod.invoke(ReflectMethod.java:35)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.nms.NMS.sendPacket(NMS.java:232)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntity(NMS_1_17.java:220)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntityLiving(NMS_1_17.java:259)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntityArmorStand(NMS_1_17.java:296)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.show(HologramLine.java:396)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$showPageTo$5(Hologram.java:453)
[02:26:54] [Server thread/WARN]: 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.Hologram.showPageTo(Hologram.java:453)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.Hologram.show(Hologram.java:441)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.HologramManager.updateVisibility(HologramManager.java:93)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.HologramManager.updateVisibility(HologramManager.java:79)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.player.PlayerListener.onJoin(PlayerListener.java:23)
[02:26:54] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor58.execute(Unknown Source)
[02:26:54] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[02:26:54] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[02:26:54] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:26:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:372)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$0(PlayerList.java:309)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1389)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[02:26:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[02:26:54] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.setAccessible(boolean)" because "com.loohp.holomobhealth.utils.NMSUtils.nmsWorldEntityManagerField" is null
[02:26:54] [Server thread/WARN]: 	at HoloMobHealth-2.3.1.0.jar//com.loohp.holomobhealth.utils.NMSUtils.getEntityUUIDFromID(NMSUtils.java:153)
[02:26:54] [Server thread/WARN]: 	at HoloMobHealth-2.3.1.0.jar//com.loohp.holomobhealth.modules.NameTagDisplay$3.onPacketSending(NameTagDisplay.java:147)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:570)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:473)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:432)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:379)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2165)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2151)
[02:26:54] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
[02:26:54] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:26:54] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.utils.reflect.ReflectMethod.invoke(ReflectMethod.java:35)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.nms.NMS.sendPacket(NMS.java:232)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntity(NMS_1_17.java:220)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntityLiving(NMS_1_17.java:259)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntityArmorStand(NMS_1_17.java:296)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.show(HologramLine.java:396)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$showPageTo$5(Hologram.java:453)
[02:26:54] [Server thread/WARN]: 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.Hologram.showPageTo(Hologram.java:453)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.Hologram.show(Hologram.java:441)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.HologramManager.updateVisibility(HologramManager.java:93)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.HologramManager.updateVisibility(HologramManager.java:79)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.player.PlayerListener.onJoin(PlayerListener.java:23)
[02:26:54] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor58.execute(Unknown Source)
[02:26:54] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[02:26:54] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[02:26:54] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:26:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:372)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$0(PlayerList.java:309)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1389)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[02:26:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[02:26:54] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.setAccessible(boolean)" because "com.loohp.holomobhealth.utils.NMSUtils.nmsWorldEntityManagerField" is null
[02:26:54] [Server thread/WARN]: 	at HoloMobHealth-2.3.1.0.jar//com.loohp.holomobhealth.utils.NMSUtils.getEntityUUIDFromID(NMSUtils.java:153)
[02:26:54] [Server thread/WARN]: 	at HoloMobHealth-2.3.1.0.jar//com.loohp.holomobhealth.modules.NameTagDisplay$3.onPacketSending(NameTagDisplay.java:147)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:570)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:473)
[02:26:54] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:432)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:379)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2165)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2151)
[02:26:54] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
[02:26:54] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:26:54] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.utils.reflect.ReflectMethod.invoke(ReflectMethod.java:35)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.nms.NMS.sendPacket(NMS.java:232)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntity(NMS_1_17.java:220)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntityLiving(NMS_1_17.java:259)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntityArmorStand(NMS_1_17.java:296)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.show(HologramLine.java:396)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$showPageTo$5(Hologram.java:453)
[02:26:54] [Server thread/WARN]: 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.Hologram.showPageTo(Hologram.java:453)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.Hologram.show(Hologram.java:441)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.HologramManager.updateVisibility(HologramManager.java:93)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.holograms.HologramManager.updateVisibility(HologramManager.java:79)
[02:26:54] [Server thread/WARN]: 	at DecentHolograms-2.7.4.jar//eu.decentsoftware.holograms.api.player.PlayerListener.onJoin(PlayerListener.java:23)
[02:26:54] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor58.execute(Unknown Source)
[02:26:54] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[02:26:54] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[02:26:54] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:26:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:372)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$0(PlayerList.java:309)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1389)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[02:26:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[02:26:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LOOHP** [comment]
#19
