### ISSUE TITLE
spam error

### ISSUE THREAD

**Issue by joaoespanhol** [LOOHP/HoloMobHealth#23]
[03:24:50 ERROR]: Could not pass event EntityDamageByBlockEvent to HoloMobHealth v2.3.4.0
java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier com.comphenix.protocol.events.PacketContainer.getDataValueCollectionModifier()'
        at com.loohp.holomobhealth.utils.DataWatcherUtils.writeMetadataPacket(DataWatcherUtils.java:64) ~[HoloMobHealth-2.3.4.0.jar:?]
        at com.loohp.holomobhealth.protocol.EntityMetadata.updateEntity(EntityMetadata.java:87) ~[HoloMobHealth-2.3.4.0.jar:?]
        at com.loohp.holomobhealth.listeners.Events.onAttack(Events.java:83) ~[HoloMobHealth-2.3.4.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor338.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:git-Paper-6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.jar:git-Paper-6]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.jar:git-Paper-6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:252) ~[paper-1.20.jar:git-Paper-6]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1056) ~[paper-1.20.jar:git-Paper-6]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:983) ~[paper-1.20.jar:git-Paper-6]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1214) ~[paper-1.20.jar:git-Paper-6]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2191) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1432) ~[?:?]
        at net.minecraft.world.entity.ambient.Bat.hurt(Bat.java:221) ~[?:?]
        at net.minecraft.world.entity.Entity.lavaHurt(Entity.java:924) ~[paper-1.20.jar:git-Paper-6]
        at net.minecraft.world.entity.Entity.baseTick(Entity.java:847) ~[paper-1.20.jar:git-Paper-6]
        at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:408) ~[?:?]
        at net.minecraft.world.entity.Mob.baseTick(Mob.java:362) ~[?:?]
        at net.minecraft.world.entity.Entity.tick(Entity.java:787) ~[paper-1.20.jar:git-Paper-6]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2972) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:435) ~[?:?]
        at net.minecraft.world.entity.ambient.Bat.tick(Bat.java:119) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1352) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:919) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:872) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.jar:git-Paper-6]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:852) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1545) ~[paper-1.20.jar:git-Paper-6]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.jar:git-Paper-6]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[paper-1.20.jar:git-Paper-6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.20.jar:git-Paper-6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.20.jar:git-Paper-6]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by LOOHP** [comment]
Your ProtocolLib is likely not update to date
