### ISSUE TITLE
java.lang.NullPointerException: Cannot read the array length because "buf" is null

### ISSUE THREAD

**Issue by xiao-k233** [LOOHP/HoloMobHealth#38]
```
[23:11:21 WARN]: java.lang.NullPointerException: Cannot read the array length because "buf" is null
[23:11:21 WARN]:        at java.base/java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:167)
[23:11:21 WARN]:        at HoloMobHealth-2.3.8.0.jar//com.loohp.holomobhealth.utils.LanguageUtils.lambda$loadTranslations$3(LanguageUtils.java:107)
[23:11:21 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:93)
[23:11:21 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:11:21 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:11:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[23:11:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[23:11:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1584)
```

**Comment by xiao-k233** [comment]
Leaves(a fork of paper) 1.21 newest commit
HoloMobHealth-2.3.8.0
zing jdk 21
linux 6.8

**Comment by xiao-k233** [comment]
# Now we have more errors
```
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because "channel" is null
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.findInjector(NettyChannelInjector.java:71)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.InjectionFactory.fromPlayer(InjectionFactory.java:105)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.getInjector(NetworkManagerInjector.java:57)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:175)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:149)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:144)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at HoloMobHealth-2.3.8.0.jar//com.loohp.holomobhealth.protocol.EntityMetadata.lambda$updateEntity$0(EntityMetadata.java:67)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:93)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1584)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because "channel" is null
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.findInjector(NettyChannelInjector.java:71)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.InjectionFactory.fromPlayer(InjectionFactory.java:105)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.getInjector(NetworkManagerInjector.java:57)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:175)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:149)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:144)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at HoloMobHealth-2.3.8.0.jar//com.loohp.holomobhealth.protocol.EntityMetadata.lambda$updateEntity$0(EntityMetadata.java:67)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:93)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1584)
[23:14:19] [Craft Scheduler Thread - 28 - HoloMobHealth/WARN]: java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because "channel" is null
[23:14:19] [Craft Scheduler Thread - 28 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.findInjector(NettyChannelInjector.java:71)
[23:14:19] [Craft Scheduler Thread - 28 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.InjectionFactory.fromPlayer(InjectionFactory.java:105)
[23:14:19] [Craft Scheduler Thread - 28 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.getInjector(NetworkManagerInjector.java:57)
[23:14:19] [Craft Scheduler Thread - 28 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:175)
[23:14:19] [Craft Scheduler Thread - 28 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:149)
[23:14:19] [Craft Scheduler Thread - 28 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:144)
[23:14:19] [Craft Scheduler Thread - 28 - HoloMobHealth/WARN]: 	at HoloMobHealth-2.3.8.0.jar//com.loohp.holomobhealth.protocol.EntityMetadata.lambda$updateEntity$0(EntityMetadata.java:67)
[23:14:19] [Craft Scheduler Thread - 28 - HoloMobHealth/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:93)
[23:14:19] [Craft Scheduler Thread - 28 - HoloMobHealth/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:14:19] [Craft Scheduler Thread - 28 - HoloMobHealth/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:14:19] [Craft Scheduler Thread - 28 - HoloMobHealth/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[23:14:19] [Craft Scheduler Thread - 28 - HoloMobHealth/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[23:14:19] [Craft Scheduler Thread - 28 - HoloMobHealth/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1584)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because "channel" is null
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.findInjector(NettyChannelInjector.java:71)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.InjectionFactory.fromPlayer(InjectionFactory.java:105)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.getInjector(NetworkManagerInjector.java:57)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:175)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:149)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:144)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at HoloMobHealth-2.3.8.0.jar//com.loohp.holomobhealth.protocol.EntityMetadata.lambda$updateEntity$0(EntityMetadata.java:67)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:93)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[23:14:19] [Craft Scheduler Thread - 12 - HoloMobHealth/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1584)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because "channel" is null
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.findInjector(NettyChannelInjector.java:71)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.InjectionFactory.fromPlayer(InjectionFactory.java:105)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.getInjector(NetworkManagerInjector.java:57)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:175)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:149)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:144)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at HoloMobHealth-2.3.8.0.jar//com.loohp.holomobhealth.protocol.EntityMetadata.lambda$updateEntity$0(EntityMetadata.java:67)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:93)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[23:14:19] [Craft Scheduler Thread - 29 - HoloMobHealth/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1584)
```

**Comment by xiao-k233** [comment]
```
 plugins
[23:15:48 INFO]: Server Plugins (28):
[23:15:48 INFO]: Bukkit Plugins:
[23:15:48 INFO]:  - Chunky, ChunkyBorder, CoreProtect, Dominion, Essentials, EssentialsChat, EssentialsSpawn, EvenMoreFish, Geyser-Spigot, GroupManager
[23:15:48 INFO]:  GSit, HoloMobHealth, ImageFrame, Kryptonite, MC_QQ, MiniMOTD, Multiverse-Core, PetBlocks, PlaceholderAPI, ProtocolLib
[23:15:48 INFO]:  RealisticSeasons, Shopkeepers, spark, squaremap, Vault, ViaBackwards, ViaVersion, WorldEdit
```

**Comment by xiao-k233** [comment]
We have More!
```
[23:23:07 WARN]: java.lang.NullPointerException
[23:23:07 WARN]: java.lang.NullPointerException
[23:23:07 WARN]: java.lang.NullPointerException
[23:23:07 WARN]: java.lang.NullPointerException
[23:23:07 WARN]: java.lang.NullPointerException
[23:23:07 WARN]: java.lang.NullPointerException
[23:23:07 WARN]: java.lang.NullPointerException
[23:23:07 WARN]: java.lang.NullPointerException
[23:23:07 WARN]: java.lang.NullPointerException
[23:23:07 WARN]: java.lang.NullPointerException
[23:23:07 WARN]: java.lang.NullPointerException
[23:23:07 WARN]: java.lang.NullPointerException
[23:23:07 WARN]: java.lang.NullPointerException
[23:23:07 WARN]: java.lang.NullPointerException
[23:23:07 WARN]: java.lang.NullPointerException
[23:23:08 WARN]: java.lang.NullPointerException
[23:23:08 WARN]: java.lang.NullPointerException
[23:23:08 WARN]: java.lang.NullPointerException
[23:23:08 WARN]: java.lang.NullPointerException
[23:23:08 WARN]: java.lang.NullPointerException
[23:23:08 WARN]: java.lang.NullPointerException
[23:23:09 WARN]: java.lang.NullPointerException
[23:23:09 WARN]: java.lang.NullPointerException
[23:23:09 WARN]: java.lang.NullPointerException
[23:23:09 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:11 WARN]: java.lang.NullPointerException
[23:23:12 WARN]: java.lang.NullPointerException
[23:23:12 WARN]: java.lang.NullPointerException
[23:23:12 WARN]: java.lang.NullPointerException
[23:23:12 WARN]: java.lang.NullPointerException
[23:23:12 WARN]: java.lang.NullPointerException
[23:23:12 WARN]: java.lang.NullPointerException
[23:23:12 WARN]: java.lang.NullPointerException
```

**Comment by xiao-k233** [comment]
I 'm sure about i'm using newest proctolLib action build.so i will issue plib tomorrow
Thank you!



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 4, 2024 23:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LOOHP/HoloMobHealth] java.lang.NullPointerException: Cannot readthe array length because "buf" is null Even More!!!!! (Issue #38)




 
The first error you posted is different from the rest.
 
For the first one, it is probably just an occasional network error when downloading language files. So it can be ignored.
 
The rest probably have something to do with ProtocolLib. Make sure you are running the latest ProtocolLib build. If the error is still here, you'd probably want to report it to ProtocolLib.
