### ISSUE TITLE
It doesn't stop throwing errors

### ISSUE THREAD

**Issue by ItsGosho** [LOOHP/HoloMobHealth#4]
[21:55:00] [Server thread/ERROR]: Could not pass event EntityDamageEvent to HoloMobHealth v2.1.0.9
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:236) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:929) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:911) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:772) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:961) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity0(EntityLiving.java:1755) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1138) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.EntityMonster.damageEntity(SourceFile:72) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.EntityZombie.damageEntity(EntityZombie.java:234) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.Entity.entityBaseTick(Entity.java:410) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.EntityLiving.entityBaseTick(EntityLiving.java:261) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.EntityInsentient.entityBaseTick(EntityInsentient.java:230) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.Entity.tick(Entity.java:367) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.EntityLiving.tick(EntityLiving.java:2338) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.EntityInsentient.tick(EntityInsentient.java:293) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.EntityZombie.tick(EntityZombie.java:170) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.WorldServer.entityJoinedWorld(WorldServer.java:659) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.World.a(World.java:751) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:394) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1104) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:846) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
        at com.loohp.holomobhealth.Utils.ParsePlaceholders.parse(ParsePlaceholders.java:39) ~[?:?]
        at com.loohp.holomobhealth.Utils.ParsePlaceholders.parse(ParsePlaceholders.java:27) ~[?:?]
        at com.loohp.holomobhealth.Modules.DamageIndicator.damage(DamageIndicator.java:319) ~[?:?]
        at com.loohp.holomobhealth.Modules.DamageIndicator.onEntityDamage(DamageIndicator.java:143) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor340.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
        ... 28 more

**Comment by ItsGosho** [comment]
I updated from Spigot 1.16.1 to 1.16.5 and the problem is gone.
