### ISSUE TITLE
[HoloMobHealth] Unable to setup languages

### ISSUE THREAD

**Issue by tncc2k** [LOOHP/HoloMobHealth#8]
Spigot 1.12.2
HoloMobHealth-2.2.2.2
Minecraft Vietnamese
HoloMobHealth-2.2.2.2 config default

[10:40:50 INFO]: [HoloMobHealth] Unable to setup languages
[10:40:50 WARN]: java.lang.NullPointerException
[10:40:50 WARN]:        at java.io.StringReader.<init>(Unknown Source)
[10:40:50 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:79)
[10:40:50 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
[10:40:50 WARN]:        at com.loohp.holomobhealth.utils.HTTPRequestUtils.getJSONResponse(HTTPRequestUtils.java:25)
[10:40:50 WARN]:        at com.loohp.holomobhealth.utils.LanguageUtils.lambda$loadTranslations$3(LanguageUtils.java:91)
[10:40:50 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[10:40:50 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[10:40:50 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[10:40:50 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[10:40:50 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by LOOHP** [comment]
Seems like it is a connection issue when downloading languages from Mojang. Make sure your server can access this sites. 
https://launchermeta.mojang.com/mc/game/version_manifest.json
http://resources.download.minecraft.net/
